version: "2"
services:
  php-fpm:
    build: ./php-fpm
    image: bobbydvo/ost_php-fpm:latest
    ports:
      - "9000:9000"
    environment:
      - APPLICATION_ENV=prod
  web:
    build: ./nginx
    image: bobbydvo/ost_nginx:latest
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80