version: "2"
services:
  php-fpm:
    build: ./php-fpm
    image: bobbydvo/ukc_php-fpm:latest
    ports:
      - "9000:9000"
    environment:
      - APPLICATION_ENV=prod
  web:
    build: ./nginx
    image: bobbydvo/ukc_nginx:latest
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
  dynamodb:
    build: ./dynamodb
    image: bobbydvo/ukc_dynamodb:latest
    ports:
      - "8000:8000"